CREATE DATABASE MY_CART;

USE MY_CART;

CREATE TABLE USER_PROFILE (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(120) NOT NULL UNIQUE,
    USER_PASSWORD VARCHAR(255) NOT NULL,
    ROLES VARCHAR(255) NOT NULL DEFAULT "USER",
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    USER_ACTIVE BOOL DEFAULT TRUE
);

CREATE TABLE CART (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    MARKETPLACE_ID INTEGER NOT NULL REFERENCES MARKETPLACE(ID),
    TOTAL NUMERIC(20,2) NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CART_ACTIVE BOOL DEFAULT TRUE
);

CREATE TABLE CART_PRODUCT (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CART_ID INTEGER NOT NULL REFERENCES CART(ID),
    PRODUCT_ID INTEGER NOT NULL REFERENCES PRODUCT(ID),
    PRODUCT_INSERT_POSITION INTEGER NOT NULL,
    QUANTITY NUMERIC(7,3) NOT NULL DEFAULT 0
);

CREATE TABLE MARKETPLACE (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    MARKETPLACE_NAME VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    MARKETPLACE_ACTIVE BOOL DEFAULT TRUE
);

CREATE TABLE PRODUCT (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    EAN VARCHAR(13),
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    PRICE NUMERIC(20,2) NOT NULL DEFAULT 0,
    IMAGE BLOB,
    CATEGORY_ID INTEGER NOT NULL REFERENCES PRODUCT_CATEGORY(ID),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    PRODUCT_ACTIVE BOOL DEFAULT TRUE
);



CREATE TABLE LIST (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE PRODUCT_LIST (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    LIST_ID INTEGER NOT NULL REFERENCES LIST(ID),
    PRODUCT_ID INTEGER NOT NULL REFERENCES PRODUCT(ID),
    QUANTITY NUMERIC(7,3) NOT NULL DEFAULT 0
);

CREATE TABLE PRODUCT_CATEGORY (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CATEGORY_DESC VARCHAR(100) NOT NULL,
    PARENT_ID INTEGER REFERENCES PRODUCT_CATEGORY(ID),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CATEGORY_ACTIVE BOOL DEFAULT TRUE
);



