# Connection properties
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_cart?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
      show_sql: true
      format_sql: true
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
# Security properties
security:
  jwt:
    signing-key: aEVTb1lAbTMwMDYzMjI0
    token-expiration: 30